In [1]:
import numpy as np 
import pandas as pd

In [2]:
import os
print(os.getcwd())

/drive/notebooks


In [3]:
movies = pd.read_csv('movies_initial.csv')

In [4]:
movies.head(1)

imdbID       title  year     rating runtime               genre released  \
0       1  Carmencita  1894  NOT RATED   1 min  Documentary, Short      NaN   

               director writer        cast  ...  imdbRating  imdbVotes  \
0  William K.L. Dickson    NaN  Carmencita  ...         5.9     1032.0   

                                              poster  \
0  https://m.media-amazon.com/images/M/MV5BMjAzND...   

                                                plot  \
0  Performing on what looks like a small wooden s...   

                                            fullplot language country awards  \
0  Performing on what looks like a small wooden s...      NaN     USA    NaN   

                     lastupdated   type  
0  2015-08-26 00:03:45.040000000  movie  

[1 rows x 21 columns]

In [5]:
movies.shape

(46014, 21)

In [6]:
#id, title, genre, keyword, plot, cast, director
movies = movies[['imdbID','title','genre','director','cast','plot','type']]


In [7]:
movies.dropna(inplace=True)

In [8]:
movies.shape

(40731, 7)

In [9]:
movies = movies[0:4000]

In [10]:
dist_type = movies['type'].unique()
print(dist_type)

['movie']


In [11]:
def collapse(L):
    L1 = ""
    for i in L:
        L1 += (i.replace(" ",""))
    return L1

In [12]:
movies['cast'] = movies['cast'].apply(collapse)
# movies['plot'] = movies['plot'].apply(collapse)
movies['genre'] = movies['genre'].apply(collapse)
movies['director'] = movies['director'].apply(collapse)

In [13]:
movies.head(3)


imdbID                                   title              genre  \
0       1                              Carmencita  Documentary,Short   
1       5                        Blacksmith Scene              Short   
3       8  Edison Kinetoscopic Record of a Sneeze  Documentary,Short   

             director                   cast  \
0  WilliamK.L.Dickson             Carmencita   
1  WilliamK.L.Dickson  CharlesKayser,JohnOtt   
3  WilliamK.L.Dickson                FredOtt   

                                                plot   type  
0  Performing on what looks like a small wooden s...  movie  
1  Three men hammer on an anvil and pass a bottle...  movie  
3  A man (Thomas Edison's assistant) takes a pinc...  movie

In [14]:

movies['genre'] = movies['genre'].apply(lambda x:x.split())
movies['director'] = movies['director'].apply(lambda x:x.split())
movies['plot'] = movies['plot'].apply(lambda x:x.split())
movies['cast'] = movies['cast'].apply(lambda x:x.split())

In [15]:
movies.head(3)

imdbID                                   title                genre  \
0       1                              Carmencita  [Documentary,Short]   
1       5                        Blacksmith Scene              [Short]   
3       8  Edison Kinetoscopic Record of a Sneeze  [Documentary,Short]   

               director                     cast  \
0  [WilliamK.L.Dickson]             [Carmencita]   
1  [WilliamK.L.Dickson]  [CharlesKayser,JohnOtt]   
3  [WilliamK.L.Dickson]                [FredOtt]   

                                                plot   type  
0  [Performing, on, what, looks, like, a, small, ...  movie  
1  [Three, men, hammer, on, an, anvil, and, pass,...  movie  
3  [A, man, (Thomas, Edison's, assistant), takes,...  movie

In [16]:
movies['tags'] = movies['cast'] + movies['genre'] + movies['director'] + movies['plot'] 

In [17]:
movies.head(1)

imdbID       title                genre              director  \
0       1  Carmencita  [Documentary,Short]  [WilliamK.L.Dickson]   

           cast                                               plot   type  \
0  [Carmencita]  [Performing, on, what, looks, like, a, small, ...  movie   

                                                tags  
0  [Carmencita, Documentary,Short, WilliamK.L.Dic...

In [18]:
new_m = movies.drop(columns=['genre','director','cast','plot', 'type'])

In [19]:
new_m.head(10)

imdbID                                              title  \
0        1                                         Carmencita   
1        5                                   Blacksmith Scene   
3        8             Edison Kinetoscopic Record of a Sneeze   
6       14                      Tables Turned on the Gardener   
7       29                                      Baby's Dinner   
9       70                                D�molition d'un mur   
10      91                             The House of the Devil   
11      75  The Conjuring of a Woman at the House of Rober...   
12     131                                   A Terrible Night   
13     132                               Une partie de cartes   

                                                 tags  
0   [Carmencita, Documentary,Short, WilliamK.L.Dic...  
1   [CharlesKayser,JohnOtt, Short, WilliamK.L.Dick...  
3   [FredOtt, Documentary,Short, WilliamK.L.Dickso...  
6   [Fran�oisClerc,Beno�tDuval, Comedy,Short, Loui...  
7   [Mrs.AugusteLumiere,Andr�eLumi�re,AugusteLumi�...  
9   [AugusteLumi�re, Documentary,Short, LouisLumi�...  
10  [Jeanned'Alcy,GeorgesM�li�s, Short,Horror, Geo...  
11  [Jeanned'Alcy,GeorgesM�li�s, Short, GeorgesM�l...  
12  [GeorgesM�li�s, Short,Comedy, GeorgesM�li�s, A...  
13  [GastonM�li�s,GeorgesM�li�s,GeorgetteM�li�s, S...

In [20]:
new_m['tags'] = new_m['tags'].apply(lambda x:','.join(x))

In [21]:
new_m.head(1)

imdbID       title                                               tags
0       1  Carmencita  Carmencita,Documentary,Short,WilliamK.L.Dickso...

In [22]:
import nltk
from nltk.stem import PorterStemmer

In [23]:
pr = PorterStemmer()

In [24]:
stem_wrds = [pr.stem(word) for word in new_m['tags']]

In [25]:
uniq_stems = list(stem_wrds)

In [26]:
new_m['tags'] = uniq_stems

In [27]:
new_m.head(1)

imdbID       title                                               tags
0       1  Carmencita  carmencita,documentary,short,williamk.l.dickso...

In [28]:
new_m['tags'][0]

'carmencita,documentary,short,williamk.l.dickson,performing,on,what,looks,like,a,small,wooden,stage,,wearing,a,dress,with,a,hoop,skirt,and,white,high-heeled,pumps,,carmencita,does,a,dance,with,kicks,and,twirls,,a,smile,always,on,her,face.'

In [29]:
new_m.head(1)

imdbID       title                                               tags
0       1  Carmencita  carmencita,documentary,short,williamk.l.dickso...

In [30]:
new_m.shape

(4000, 3)

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [32]:
vectors = cv.fit_transform(new_m['tags']).toarray()

In [33]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [35]:
c = cv.get_feature_names_out()

In [36]:
from sklearn.metrics.pairwise import cosine_similarity

In [37]:
similarity = cosine_similarity(vectors)

In [38]:
similarity[8]


array([0.0521286 , 0.08512565, 0.09325048, ..., 0.08025724, 0.08025724,
       0.04662524])

In [39]:
def recommend(movie):
    index = new_m[new_m['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_m.iloc[i[0]].title)

In [40]:
recommend("Superman")

Barabbas
Aelita: Queen of Mars
The Last Days of Pompeii
Kim
In Which We Serve


In [41]:
# import pickle

In [ ]:
# pickle.dump(new_m.to_dict(),open('movie_list.pkl','wb'))
# pickle.dump(similarity,open('similarity.pkl','wb'))